"""empty message

Revision ID: e1b3904e5905
Revises: f965f62efbe0
Create Date: 2022-11-04 19:17:46.300117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1b3904e5905'
down_revision = 'f965f62efbe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('description', sa.String(), nullable=True))
    op.drop_column('task', 'descritpion')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('descritpion', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('task', 'description')
    # ### end Alembic commands ###
